-define(conn, rabbitconn).
-define(ch, ch4_genrs).
-define(queue, <<"queue4_dstats">>).
-define(exch, <<"exch4_genrs">>).
-record(amqp_connect_args, {exch, queue}).
-record(pub, {payload}).
-record(cask4_consumer_msg, {from}).
-define(amqp_consumer_proc, amqp_consumer_process).
-define(amqp_pub_proc, amqp_pub_process).
