-define(server_node, 'resa_server@localhost.jpat.org').
-define(server_node_short, 'resa_server@localhost').
-define(client_node, 'resa_client@localhost.jpat.org').
-record(attempt2free, {resource}).
