-record(allocate_resource, {server, from_pid}).
-record(free_resource, {server, from_pid, resource}).
-record(data_structure, {free, allocated}).
-record(server_request_data, {server}).
-record(handler_reply, {message}).
-record(handler_reply_data, {data=#data_structure{}}).
-record(request_stats, {from_pid, free, allocated}).
